source 'https://github.com/yohunl/yohunlSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CYKitPod_Example' do
  pod 'CYKitPod', :path => '../'

  target 'CYKitPod_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
